name: Publish Commit
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Build package
        run: bun run build

      - run: bunx pkg-pr-new publish
