name: Publish Commit ⚙️

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # check author permissions
  check:
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result }}
    steps:
      - name: Check permissions
        id: checkPermissions
        uses: actions-cool/check-user-permission@v2
        with:
          # require repo write access to trigger the package preview
          require: "write"
  # build and publish the preview package
  publish:
    needs: check
    # publish the preview package only if permissions check passed
    if: needs.check.outputs.has-permissions == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun i
      - name: Build package
        run: bun run build
      - name: Publish package
        run: bunx pkg-pr-new publish
